export enum EmitSubscribe {
  SERVER_MESSAGE = 'SERVER_MESSAGE',
  CLIENT_MESSAGE = 'CLIENT_MESSAGE',
  SERVER_MESSAGE_DELETE = 'SERVER_MESSAGE_DELETE',
  CLIENT_MESSAGE_DELETE = 'CLIENT_MESSAGE_DELETE',
  CLIENT_MESSAGE_EDIT = 'CLIENT_MESSAGE_EDIT',
  SERVER_MESSAGE_EDIT = 'SERVER_MESSAGE_EDIT',
  SERVER_DIALOG = 'SERVER_DIALOG',
  CLIENT_DIALOG = 'CLIENT_DIALOG',
  LEAVE_DIALOG = 'LEAVE_DIALOG',
}

export enum Errors {
  INVAlID_AUTH = 'INVALID_AUTH',
  EMPTY_TOKEN = 'EMPTY_TOKEN',
}
